### PR TITLE
Add AFTLocal

### PR DESCRIPTION
**Pull request by Datta0**

### CODE REVIEW

**Comment by rish-16** [comment]
Hey, 

Thank you for the amazing contribution! 

I'm in talks with the primary author of the paper and we're trying to find a convention to best present this module. I'll inform you of these conventions once I have more details with me. We can work it out and then merge your code into the master branch.

Appreciate your patience 😄

**Comment by Datta0** [comment]
Yeah that'd be cool.
I'm a little iffy about `wbias`.
Like declaring it as a torch random tensor, then using lists for replacing elements and converting back to torch tensor.

Can we improve it?

**Comment by rish-16** [comment]
Yup, I have a patch that's WIP. It brings back `wbias` into `__init__` instead of `forward`. 

See #3 for more details. I explain my rationale for the (temporary) hacky implementation. Definitely due for change in accordance with the equations in the paper.

**Comment by rish-16** [comment]
Hello, appreciate your patience!

I've added in the latest patch with the author-approved implementation of `AFTFull`. Do check if you can change your implementation to match the code style used.

Thank you once again for your help!

**Pull request closed without merging**
